server:
  port: 8080

spring:
  application:
    name: Unbound Preaching
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url:      jdbc:mysql://127.0.0.1:3306/unbound?serverTimezone=UTC
    username: root
    password:
    hikari:
      minimumIdle:       1
      maximumPoolSize:   1
      idleTimeout:       30000
      maxLifetime:       2000000
      connectionTimeout: 30000
  jpa:
    hibernate:
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      dialect: org.hibernate.dialect.MySQL8Dialect
      ddl-auto: none
  data:
    rest:
      base-path: /api
webapp.url: http://localhost:4200


---
spring:
  config.activate.on-profile: prod
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: bvhb7i3juenx2w11
    password: dx5m2uqq4aygv6lz
  jpa.properties.hibernate.dialect: org.hibernate.dialect.MySQL8Dialect
webapp.url: https://unboundpreaching.netlify.app
---

#logging:
#  level:
#    org.springframework: ERROR
#    org.springframework.context.support.[PostProcessorRegistrationDelegate$BeanPostProcessorChecker]: WARN
